//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanban
{
    using System;
    using System.Collections.Generic;
    
    public partial class avatar
    {
        public avatar()
        {
            this.usuario = new HashSet<usuario>();
            this.usuario1 = new HashSet<usuario>();
        }
    
        public int id { get; set; }
        public string path_avatar { get; set; }
    
        public virtual ICollection<usuario> usuario { get; set; }
        public virtual ICollection<usuario> usuario1 { get; set; }
    }
}
