//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanban
{
    using System;
    using System.Collections.Generic;
    
    public partial class avatar
    {
        public avatar()
        {
            this.usuario = new HashSet<usuario>();
            this.usuario1 = new HashSet<usuario>();
        }
    
        public int id { get; set; }
        public string path_avatar { get; set; }
    
        public virtual ICollection<usuario> usuario { get; set; }
        public virtual ICollection<usuario> usuario1 { get; set; }
    }
}
