//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanban
{
    using System;
    using System.Collections.Generic;
    
    public partial class fases
    {
        public fases()
        {
            this.grupo_usuarios_x_fases = new HashSet<grupo_usuarios_x_fases>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public bool ativo { get; set; }
    
        public virtual ICollection<grupo_usuarios_x_fases> grupo_usuarios_x_fases { get; set; }
    }
}
