//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanban
{
    using System;
    using System.Collections.Generic;
    
    public partial class fases
    {
        public fases()
        {
            this.grupo_usuarios_x_fases = new HashSet<grupo_usuarios_x_fases>();
            this.tarefas = new HashSet<tarefas>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public bool ativo { get; set; }
        public Nullable<int> projetoId { get; set; }
    
        public virtual ICollection<grupo_usuarios_x_fases> grupo_usuarios_x_fases { get; set; }
        public virtual ICollection<tarefas> tarefas { get; set; }
    }
}
