//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanban
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_usuario_x_permissao
    {
        public int id { get; set; }
        public Nullable<int> id_permissao { get; set; }
        public Nullable<int> id_grupo_usuario { get; set; }
    
        public virtual grupo_usuarios grupo_usuarios { get; set; }
        public virtual grupo_usuarios grupo_usuarios1 { get; set; }
        public virtual permissao permissao { get; set; }
        public virtual permissao permissao1 { get; set; }
    }
}
