//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanban
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KANBANEntities : DbContext
    {
        public KANBANEntities()
            : base("name=KANBANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<avatar> avatar { get; set; }
        public DbSet<classificacao> classificacao { get; set; }
        public DbSet<fases> fases { get; set; }
        public DbSet<grupo_usuario_x_permissao> grupo_usuario_x_permissao { get; set; }
        public DbSet<grupo_usuarios> grupo_usuarios { get; set; }
        public DbSet<grupo_usuarios_x_fases> grupo_usuarios_x_fases { get; set; }
        public DbSet<permissao> permissao { get; set; }
        public DbSet<projeto> projeto { get; set; }
        public DbSet<projeto_x_usuario> projeto_x_usuario { get; set; }
        public DbSet<sprints> sprints { get; set; }
        public DbSet<status> status { get; set; }
        public DbSet<tarefa_x_comentario> tarefa_x_comentario { get; set; }
        public DbSet<tarefa_x_usuario> tarefa_x_usuario { get; set; }
        public DbSet<tarefas> tarefas { get; set; }
        public DbSet<tipo> tipo { get; set; }
        public DbSet<usuario> usuario { get; set; }
        public DbSet<usuario_x_grupos_usuario> usuario_x_grupos_usuario { get; set; }
    }
}
