//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanban
{
    using System;
    using System.Collections.Generic;
    
    public partial class permissao
    {
        public permissao()
        {
            this.grupo_usuario_x_permissao = new HashSet<grupo_usuario_x_permissao>();
            this.grupo_usuario_x_permissao1 = new HashSet<grupo_usuario_x_permissao>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
    
        public virtual ICollection<grupo_usuario_x_permissao> grupo_usuario_x_permissao { get; set; }
        public virtual ICollection<grupo_usuario_x_permissao> grupo_usuario_x_permissao1 { get; set; }
    }
}
