//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanban
{
    using System;
    using System.Collections.Generic;
    
    public partial class projeto
    {
        public projeto()
        {
            this.projeto_x_usuario = new HashSet<projeto_x_usuario>();
            this.projeto_x_usuario1 = new HashSet<projeto_x_usuario>();
            this.tarefas = new HashSet<tarefas>();
            this.tarefas1 = new HashSet<tarefas>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public string titulo { get; set; }
    
        public virtual ICollection<projeto_x_usuario> projeto_x_usuario { get; set; }
        public virtual ICollection<projeto_x_usuario> projeto_x_usuario1 { get; set; }
        public virtual ICollection<tarefas> tarefas { get; set; }
        public virtual ICollection<tarefas> tarefas1 { get; set; }
    }
}
