//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanban
{
    using System;
    using System.Collections.Generic;
    
    public partial class projeto
    {
        public projeto()
        {
            this.projeto_x_usuario = new HashSet<projeto_x_usuario>();
            this.projeto_x_usuario1 = new HashSet<projeto_x_usuario>();
            this.tarefas = new HashSet<tarefas>();
            this.tarefas1 = new HashSet<tarefas>();
            this.sprints = new HashSet<sprints>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public string titulo { get; set; }
    
        public virtual ICollection<projeto_x_usuario> projeto_x_usuario { get; set; }
        public virtual ICollection<projeto_x_usuario> projeto_x_usuario1 { get; set; }
        public virtual ICollection<tarefas> tarefas { get; set; }
        public virtual ICollection<tarefas> tarefas1 { get; set; }
        public virtual ICollection<sprints> sprints { get; set; }
    }
}
