//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanban
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarefa_x_comentario
    {
        public int id { get; set; }
        public int id_tarefas { get; set; }
        public Nullable<System.DateTime> dt_comentário { get; set; }
        public string descricao { get; set; }
        public string anexo { get; set; }
    
        public virtual tarefas tarefas { get; set; }
        public virtual tarefas tarefas1 { get; set; }
    }
}
