//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanban
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarefa_x_usuario
    {
        public int id { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_tarefas { get; set; }
        public Nullable<bool> ativo { get; set; }
        public Nullable<int> id_usuario_proximo { get; set; }
        public Nullable<System.DateTime> dt_criacao { get; set; }
        public Nullable<int> id_grupo_usuarios_proximo { get; set; }
        public Nullable<int> indice { get; set; }
        public Nullable<System.DateTime> dt_inicio_tarefa { get; set; }
        public Nullable<System.DateTime> dt_fim_tarefa { get; set; }
    
        public virtual grupo_usuarios grupo_usuarios { get; set; }
        public virtual tarefas tarefas { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
