//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanban
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_x_grupos_usuario
    {
        public int id { get; set; }
        public Nullable<int> id_grupos_usuario { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual grupo_usuarios grupo_usuarios { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
